[package]
name = "core"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.32", features = ["derive", "env"] }
sqlx = { version = "0.8", features = [ "runtime-tokio", "sqlite", "rust_decimal" ] }
tokio.workspace = true

